# These are supported funding model platforms

# GitHub usernames supported for sponsorship
github:
  - ritwikdurga

# Additional information or informative comment
# The listed GitHub username 'ritwikdurga' supports sponsorship for our project.
# This file showcases platforms where contributions and sponsorships are accepted.
# Please add any other relevant platforms or usernames as needed.
